kind: Deployment
apiVersion: apps/v1
metadata:
  name: spring-boot
  namespace: default
  generation: 2
  labels:
    k8s-app: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: spring-boot
  template:
    metadata:
      name: spring-boot
      labels:
        k8s-app: spring-boot
    spec:
      containers:
        - name: spring-boot
          image: 'akvone/sandbox-spring-boot:1.0-SNAPSHOT'
          resources: { }
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: false
          ports:
            - name: main
              containerPort: 8080
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext: { }
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600