# Initially copied from https://hub.docker.com/_/postgres

# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: sandbox
      POSTGRES_USER: sandbox
      POSTGRES_DB: sandbox
    ports:
      - 5432:5432