management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      post:
        enabled: true
spring:
  config:
    import:
      - feature_config/properties-state.yaml
      - feature_config/encrypted-properties.yaml