spring:
  config:
    import:
      - feature_config/profile/main.yaml
      - feature_config/actuator.yaml
      - feature_config/caching.yaml
      - feature_config/dynamic_properties.yaml
      - feature_config/properties_conversion.yaml
  main:
    cloud-platform: kubernetes
  profiles:
    active: prod, feature-jcache