management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  config:
    import:
      - classpath:prod.properties
      - classpath:dev[.yaml]
  main:
    cloud-platform: kubernetes
  profiles:
    active: prod

modules:
  properties:
    defaultTimeout: -1
    newDefaultTimeout: 999d