management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
spring:
  config:
    import:
      - classpath:config/profile/dev[.yaml]
      - classpath:config/profile/prod.properties
      - classpath:config/properties/properties.yaml
  main:
    cloud-platform: kubernetes
  profiles:
    active: prod
  cache:
    cache-names: "main"
    type: jcache