spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/sandbox"
    username: "postgres"
    password: "postgres"

#logging:
#  level:
#    org.springframework: debug