spring:
  config:
    import:
      - shared/actuator.yaml
      - shared/server.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/sandbox"
    username: "sandbox"
    password: "sandbox"

#logging:
#  level:
#    org.springframework: debug