spring:
  application:
    name: spring-cloud-zuul-1
  sleuth:
    zuul:
      enabled: true
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug

zuul:
  routes:
    sandbox: # You may use https://getsandbox.com/ to generate a stab
      path: /sandbox/**
      sensitiveHeaders: [ ]
      url: https://morning-haze-715.getsandbox.com:443